# An example configuration file for an EVM provider with the following addons and extensions:
# - archive
# - debug
# - trace

# ** Replace the urls with your own node urls **

endpoints:
    - api-interface: jsonrpc
      chain-id: ETH1 # Replace the chain-id for any relevant spec that inherits EVM (e.g. ETH1, FTM250, CELO, ARBITRUM,BASE, BSC, POLYGON, BLAST, FANTOM, SEPOLIA, etc.)
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: http://8.52.134.76:7781
          addons:
            - archive
        - url: ws://207.121.25.84:336/bsc-archival-ws/
          addons:
            - archive
        - url: http://8.52.134.76:7781
          addons:
            - archive
            - debug
        - url: ws://207.121.25.84:336/bsc-archival-ws/
          addons:
            - archive
            - debug
        - url: http://8.52.134.76:7781
          addons:
            - archive
            - trace
        - url: ws://207.121.25.84:336/bsc-archival-ws/
          addons:
            - archive
            - trace
        - url: http://127.0.0.18:8575
          addons:
            - debug
        - url: ws://127.0.0.18:8576
          addons:
            - debug
        - url: http://8.52.134.76:7781
          addons:
            - trace
        - url: ws://207.121.25.84:336/bsc-archival-ws/
          addons:
            - trace
        - url: http://127.0.0.18:8575
        - url: ws://127.0.0.18:8576
        